apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: deny-update-scc-anyuid
spec:
  background: false
  rules:
    - match:
        any:
          - resources:
              kinds:
                - SecurityContextConstraints
              names:
                - anyuid
                - hostaccess
                - hostmount-anyuid
                - hostnetwork
                - node-exporter
                - nonroot
                - privileged
                - restricted
      name: anyuid
      preconditions:
        any:
          - key: '{{ request.operation }}'
            operator: Equals
            value: CREATE
          - key: '{{ request.operation }}'
            operator: Equals
            value: UPDATE
          - key: '{{ request.operation }}'
            operator: Equals
            value: DELETE
      validate:
        deny: {}
        message: Cannot edit the SCC anyuid
  validationFailureAction: enforce
