apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: block-modify-default-sccs
spec:
  rules:
  - name: block-modify-default-sccs
    match:
      metadata:
        name:
        - anyuid
        - hostaccess
        - hostmount-anyuid
        - hostnetwork
        - node-exporter
        - nonroot
        - privileged
        - restricted
    resource:
      resources:
      - scc
    operations:
      - create
      - update
      - patch
      - delete
    deny:
      message: Modifying default Security Context Constraints is not allowed.

