---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/component: kyverno
    app: kyverno
    app.kubernetes.io/name: kyverno
    app.kubernetes.io/part-of: kyverno
  name: kyverno
